[PRODUCTION]
    SECRET_KEY = 'change_me'
    PASSWORD_HASH = 'change_me'
    UPLOAD_FOLDER = 'backups'
[TESTING]
    SECRET_KEY = 'change_me'
    PASSWORD_HASH = 'change_me'
    UPLOAD_FOLDER = 'backups'
[DEVELOPMENT]
    SECRET_KEY = 'change_me'
    PASSWORD_HASH = 'change_me'
    UPLOAD_FOLDER = 'backups'
