[PRODUCTION]
    SECRET_KEY = 'change_me'
    PASSWORD_HASH = 'change_me'
    UPLOAD_FOLDER = 'backups'
    BACKUPS_TO_SAVE = 7
    [PRODUCTION.LOGGING]
    LOGLEVEL = 'INFO'
    LOG_TO_FILE = false
    LOGFILE = '/var/log/ddmail_backup_receiver.log'
    LOG_TO_SYSLOG = true
    SYSLOG_SERVER = '/dev/log'
[TESTING]
    SECRET_KEY = 'change_me'
    PASSWORD_HASH = 'change_me'
    UPLOAD_FOLDER = 'backups'
    BACKUPS_TO_SAVE = 7
    [TESTING.LOGGING]
    LOGLEVEL = 'DEBUG'
    LOG_TO_FILE = true
    LOGFILE = '/var/log/ddmail_backup_receiver.log'
    LOG_TO_SYSLOG = false
    SYSLOG_SERVER = '/dev/log'
[DEVELOPMENT]
    SECRET_KEY = 'change_me'
    PASSWORD_HASH = 'change_me'
    UPLOAD_FOLDER = 'backups'
    BACKUPS_TO_SAVE = 7
    [DEVELOPMENT.LOGGING]
    LOGLEVEL = 'DEBUG'
    LOG_TO_FILE = true
    LOGFILE = '/var/log/ddmail_backup_receiver.log'
    LOG_TO_SYSLOG = false
    SYSLOG_SERVER = '/dev/log'
